### ISSUE TITLE
Expose personal_sign, eth_signTransaction event

### ISSUE THREAD

**Issue by hewigovens** [WalletConnect/kotlin-walletconnect-lib#11]
current only `eth_sign` and `eth_sendTransaction` are handled
```kotlin
private fun ByteArray.toMethodCall(): Session.MethodCall =
        String(this).let { json ->
            mapAdapter.fromJson(json)?.let {
                try {
                    val method = it["method"]
                    when (method) {
                        "wc_sessionRequest" -> it.toSessionRequest()
                        "wc_sessionUpdate" -> it.toSessionUpdate()
                        "eth_sendTransaction" -> it.toSendTransaction()
                        "eth_sign" -> it.toSignMessage()
                        null -> it.toResponse()
                        else -> it.toCustom()
                    }
                } catch (e: Exception) {
                    throw Session.MethodCallException.InvalidRequest(it.getId(), "$json (${e.message ?: "Unknown error"})")
                }
            } ?: throw IllegalArgumentException("Invalid json")
        }
```

**Comment by pedrouid** [comment]
**Ethereum JSON-RPC API Methods**
https://docs.walletconnect.org/json-rpc/ethereum

**Comment by hewigovens** [comment]
Hi, any updates for this?

**Comment by rmeissner** [comment]
You can access them via the custom requests. All incomming requests are currently exposed (even the wallet connect related once, but that might change). 

Feel free to add the missing mappings from the docs linked :) 

If you don't see the request as a custom request then this is a bug an we should investigate ;)

@pedrouid should we only map the requests mentioned in the docs or should we make a list of all requests related to the wallet accounts (e.g. eth_accounts, not sure what others might be important)

**Comment by hewigovens** [comment]
@rmeissner I know we can get it from custom event, but it make more sense to reuse the same model for `eth_signTransaction` and `eth_sendTransaction` and handle the param order inside this lib

**Comment by EthanChenccc** [comment]
> **Ethereum JSON-RPC API Methods** https://docs.walletconnect.org/json-rpc/ethereum

How can I call   personal_sign
