### ISSUE TITLE
Not connecting with metamask

### ISSUE THREAD

**Issue by papanmanna** [WalletConnect/kotlin-walletconnect-lib#36]

**Comment by ligi** [comment]
please provide more information

**Comment by papanmanna** [comment]
after click on connect button on sample app, a dialog is coming which contains the list of application like metamask, Argent, trustwallet. If I select metamask then It redirect to metamask app. But in metamask app, there is no popup coming for connection establishment. If I go back to the sample app, It shows disconnect button and address is null.

**Comment by buckyass1** [comment]
Hi @papanmanna, i guess i can help you with this. But i need to see your code.
