### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by SephirothLT** [WalletConnect/kotlin-walletconnect-lib#6]
How to connect and invoke sign?  Is this library not finish yet?

**Comment by ligi** [comment]
signing is implemented - see how to e.g. use it here:

https://github.com/walleth/walleth/blob/master/app/src/main/java/org/walleth/activities/walletconnect/WalletConnectConnectionActivity.kt#L59

Is this what you where looking for?

**Comment by SephirothLT** [comment]
yes ,I think it's better to add more test code and more Text in README,Thanks!

**Comment by SephirothLT** [comment]
![image](https://user-images.githubusercontent.com/20485889/57441856-5e4b9180-727d-11e9-9108-bddbdb48f416.png)
When I try to analyze this params ,this error cooured?How to solve it?Thanks! @ligi

**Comment by ligi** [comment]
this looks more of a general programming question - so perhaps try stackoverflow?

**Comment by SephirothLT** [comment]
Oh！ I‘ll try  Thanks!
