### ISSUE TITLE
How to sign ether transaction?

### ISSUE THREAD

**Issue by Serpivskyi** [WalletConnect/kotlin-walletconnect-lib#60]
Hi, I receive this:
SendTransaction(id=1643806348107256, from=0x47a1d3cf6908263372d737655d6084c377040f1f, to=0xd4a57a3bd3657d0d46b4c5bac12b3f156b9b886b, nonce=null, gasPrice=null, gasLimit=null, value=0x3a43b68e51000, data=0xe99a3f80...
I sign transaction, and get hash -> 0xd887b7bbdaabe5fdc21625fd41c44ec014323549518dd6aac96b65d636e33299.
But what next? I am trying to do session?.performMethodCall(sign), but nothing happens

**Comment by qm921** [comment]
May I ask where did you call the method to obtain the signature and the signature?
