### ISSUE TITLE
How do I sign with personal_sign

### ISSUE THREAD

**Issue by jiaweio** [WalletConnect/kotlin-walletconnect-lib#73]
val from = ExampleApplication.session.approvedAccounts()?.first() ?: return
        Log.i(TAG, "---click-->$from")
        ExampleApplication.session.performMethodCall(
            Session.MethodCall.Custom(
                System.currentTimeMillis(),
                "personal_sign",
                arrayListOf(
                    "0xdeadbeaf", from)
            )
        ) { response ->
            Log.d(TAG, "------>{response.result}--->{response.error}") 
}

I use the Custom method, but I get no response, I can't find what the problem is

**Comment by SnailMyth** [comment]
和signMessage一样的处理方式,把签名hash传出去就行了

**Comment by jiaweio** [comment]
> 

你好，我是用Custom 这种签名方式，无法拿到任何响应内容，也不会唤起metamask ，我不太明白你说的这种signMessage 是怎样签名的，有具体的实现代码么，感谢

**Comment by jiaweio** [comment]
> 和signMessage一样的处理方式,把签名hash传出去就行了

你好，我尝试使用custom Api 进行persnal sign 进行签名，但是跳转到metamask 后没有任何反应，不会显示弹窗，不知道是为什么 想问下是我传递的参数不对导致的么

**Comment by wjx0805** [comment]
> 我是这样解决的

初始化的时候 Session.PeerMeta(name = "demo", url = "xx.xx.xx.") ,url必传,

原因查的是 MetaTask 5.3.0之后会检验appurl. 我加上参数后可以获取签名了

**Comment by jiaweio** [comment]
> > 我是这样解决的
> 
> 初始化的时候 Session.PeerMeta(name = "demo", url = "xx.xx.xx.") ,url必传,
> 
> 原因查的是 MetaTask 5.3.0之后会检验appurl. 我加上参数后可以获取签名了

好的，感谢你的回复，已经找到原因了
