### ISSUE TITLE
approveRequest has question ?

### ISSUE THREAD

**Issue by SephirothLT** [WalletConnect/kotlin-walletconnect-lib#8]
when i invoke session.approveRequest(mCalledId,json)
mCalledId=1557716792569829
json{"signature":"a6003141600a3327190de4d6c0c25392e148902ddd8a79398bdaccba977febbb4abed804dd9b6cd72ceb1a4754baa239fa295cbdbcbf017133a8cbe0723fae67","publicKey":"0434f5d2f2c90b1bcdb7875775b702fe0c440993dbfe88f9101657d4b2081f01e181272df52eefdee77eed40762b3d013baea3d34281f0b772115316351e376cc6"}

but after invoked,the broswer just exit my bnb account and jump to Homepage!
Can you give me some advice?

**Comment by SephirothLT** [comment]
Solved!

**Comment by qm921** [comment]
I can connect with metamask according to the demo, but I don't know what parameters to pass and which method to call to get the signature, can you explain it to me, or give me a demo you wrote successfully

**Comment by nsaun-dq** [comment]
@SephirothLT @qm921 any updates on this?
