### ISSUE TITLE
sell and buy problem

### ISSUE THREAD

**Issue by liweiww123** [WalletConnect/kotlin-walletconnect-lib#9]
Why does the website always send a same message to the phone when the transaction is initiated?

Balance transfer will not.

Why?

**Comment by rmeissner** [comment]
Hello,

which websites are you referring to (please provide an url)? Also what clients/ sdks are you using for testing? What issues do you encounter when using the kotlin library and how did you integrate it?

Answering these would help us in addressing your issue ;)

**Comment by liweiww123** [comment]
the website url is:
https://testnet.binance.org/

Is using Kotlin library on the android wallet，Dealing with the business of binance.

I don't know if this problem is caused by your library or the Binance website.

**Comment by rmeissner** [comment]
For me wallet-connect is not available on `https://testnet.binance.org/` therefore I cannot really test it. Also I am not sure how the sdk is integrated into their website. But it doesn't seem likely that this is related to the mobile sdk.

What message are you receiving on your phone? Also have you tested other wallets?

**Comment by pedrouid** [comment]
Not a WalletConnect problem, please refer to https://github.com/binance-chain
